### ISSUE TITLE
Err: fs.readFileSync() is not a funtion

### ISSUE THREAD

**Issue by prasanthmpr** [vinaybedre/exchange-web-service#4]
Using this in ionic project

After installing and configuring "Exchange-web-service", am getting the error as fs.readFileSync() is not a funtion.

Anyone come across this issue? Please let ne know.

**Comment by vinaybedre** [comment]
Hi,

How are you using ews? can you paste some sample code?

**Comment by prasanthmpr** [comment]
Am using this in ionic..

import { Component } from '@angular/core';
import { NavController, NavParams } from 'ionic-angular';

/**
 * Generated class for the NodeewsPage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */
@Component({
  selector: 'page-nodeews',
  templateUrl: 'nodeews.html',
})
export class NodeewsPage {
  ews:any = require("exchange-web-service");

  constructor(public navCtrl: NavController, public navParams: NavParams) {

  }

  connect() {
    this.ews.config('username', 'password', 'https://mail.example.com/Ews/Exchange.asmx', 'domain');
    this.ews.sendMail('emailid', 'Hello', 'Mail from EWS');
  }
}

**Comment by vinaybedre** [comment]
Looking at the code, it's not clear why are you getting the error, I cross verified from my end and issue doesn't exist. Try to debug via visual studio code and check

**Comment by prasanthmpr** [comment]
Let me know one thing please. Have you tested it in ionic project? Will it work in ionic?

**Comment by vinaybedre** [comment]
@prasanthmpr  I didn't check on Ionic project, but a node js project. But none the less, it should work.
